name: Build image

on:
  push:
    branches: master

jobs:
  build:
    strategy:
      matrix:
        arch: [linux/386, linux/amd64, linux/arm64, linux/arm/v7]
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      -
        name: Run Buildx
        run: |
          docker buildx build \
            --platform ${{ matrix.arch }} \
            --tag quay.io/phyrog/librespot:latest \
            --file ./Dockerfile .
